import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>ARFF BXW</title>
      <body className={inter.className}>
        <div className=" text-stone-800 z-10 bg-[radial-gradient(#d1d1d1_1px,transparent_1px)] bg-repeat bg-center w-full h-full [background-size:32px_32px]">
          {children}
        </div>
      </body>
    </html>
  );
}
